---
- name: Create passwordless sudouser
  hosts: all
  become: True
  tasks:

    - name: create new system group
      group: >
        name=newsudo
        system=yes
        state=present

    - name: create new user
      user: name=passwdlessuser group=newsudo

    - name: create temporary sudoers file
      command: cp /etc/sudoers /etc/sudoers.d/sudoers.tmp

    - name: set NOPASSWD option to created group
      lineinfile:
        dest: /etc/sudoers.d/sudoers.tmp
        regexp: '^%newsudo'
        line: '%newsudo   ALL=(ALL) NOPASSWD:ALL'

    - name: ensure that file is properly configured
      command: visudo -c -f /etc/sudoers.d/sudoers.tmp

    - name: replace main sudoers file with temporary
      command: cp /etc/sudoers.d/sudoers.tmp /etc/sudoers

    - name: delete temporary sudoers file
      file:
        path: /etc/sudoers.d/sudoers.tmp
        state: absent
