---
- name: Create passwordless sudouser
  hosts: all
  become: True
  tasks:

    - name: create new system group
      group: >
        name=newsudo
        system=yes
        state=present

    - name: create new user
      user: name=passwdlessuser group=newsudo

    - name: set NOPASSWD option to created group
      lineinfile:
        dest: /etc/sudoers
        regexp: '^%newsudo'
        line: '%newsudo   ALL=(ALL) NOPASSWD:ALL'

    - name: ensure that file is properly configured
      command: visudo -c -f /etc/sudoers
